"use client";

import * as React from "react";
import { BarChart3, Check, Code2, FileText, ImageIcon, Link2, Loader2, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getCalculatorName } from "@/lib/platform-features";

type ActionState = "idle" | "loading" | "success";

const actions = [
  { id: "embed", label: "Embed", icon: Code2 },
  { id: "compare", label: "Compare", icon: BarChart3 },
  { id: "report", label: "Report", icon: FileText },
  { id: "image", label: "Image", icon: ImageIcon },
  { id: "share", label: "Share", icon: Link2 },
  { id: "save", label: "Save Scenario", icon: Save },
] as const;

export function ActionToolbar({ pathname }: { pathname: string }) {
  const [activeAction, setActiveAction] = React.useState<string | null>(null);
  const [actionState, setActionState] = React.useState<ActionState>("idle");
  const [message, setMessage] = React.useState("Ready");
  const calculatorName = getCalculatorName(pathname);

  const runAction = async (actionId: string) => {
    setActiveAction(actionId);
    setActionState("loading");

    try {
      const url = `${window.location.origin}${pathname}`;
      const embed = `<iframe src="${url}" title="${calculatorName}" width="100%" height="720" loading="lazy"></iframe>`;

      if (actionId === "share" && navigator.share) {
        await navigator.share({ title: calculatorName, url });
        setMessage("Shared");
      } else if (actionId === "embed") {
        await navigator.clipboard.writeText(embed);
        setMessage("Embed copied");
      } else if (actionId === "share") {
        await navigator.clipboard.writeText(url);
        setMessage("Link copied");
      } else if (actionId === "save") {
        const saved = JSON.parse(
          (localStorage.getItem("calcipro-scenarios") || localStorage.getItem("calcverse-scenarios")) || "[]"
        ) as unknown[];
        localStorage.setItem(
          "calcipro-scenarios",
          JSON.stringify([{ name: calculatorName, url, savedAt: new Date().toISOString() }, ...saved].slice(0, 25))
        );
        setMessage("Scenario saved");
      } else if (actionId === "report") {
        window.print();
        setMessage("Report ready");
      } else if (actionId === "image") {
        const imageMarkup = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="100%" height="100%" fill="#111827"/><text x="60" y="120" fill="#ffffff" font-family="Arial" font-size="52" font-weight="700">${calculatorName}</text><text x="60" y="190" fill="#d1d5db" font-family="Arial" font-size="28">Generated by CalciPro</text><text x="60" y="540" fill="#9ca3af" font-family="Arial" font-size="24">${url}</text></svg>`;
        const link = document.createElement("a");
        link.href = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(imageMarkup)}`;
        link.download = `${calculatorName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-result.svg`;
        link.click();
        setMessage("Image exported");
      } else {
        setMessage("Compare mode ready");
      }

      setActionState("success");
    } catch {
      setMessage("Action unavailable");
      setActionState("idle");
    }

    window.setTimeout(() => {
      setActionState("idle");
      setActiveAction(null);
      setMessage("Ready");
    }, 1600);
  };

  return (
    <section
      className="sticky top-20 z-40 mb-8 rounded-xl border bg-background/75 p-2 shadow-lg shadow-black/5 backdrop-blur-xl supports-[backdrop-filter]:bg-background/55"
      aria-label="Calculator action toolbar"
    >
      <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
        <div className="flex gap-2 overflow-x-auto pb-1 md:pb-0">
          {actions.map((action) => {
            const Icon = action.icon;
            const isActive = activeAction === action.id;

            return (
              <Button
                key={action.id}
                type="button"
                variant={isActive ? "default" : "ghost"}
                size="sm"
                className="shrink-0 gap-2 rounded-lg"
                title={action.label}
                aria-label={action.label}
                disabled={actionState === "loading"}
                onClick={() => void runAction(action.id)}
              >
                {isActive && actionState === "loading" ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                {isActive && actionState === "success" ? <Check className="h-4 w-4" /> : null}
                {!isActive || actionState === "idle" ? <Icon className="h-4 w-4" /> : null}
                <span>{action.label}</span>
              </Button>
            );
          })}
        </div>
        <p className="px-2 text-xs font-medium text-muted-foreground" aria-live="polite">
          {message}
        </p>
      </div>
    </section>
  );
}
