import { constructMetadata } from "@/seo/seo-utils";

export const metadata = constructMetadata({
  canonical: "https://calcipro-phi.vercel.app/terms",
  title: "Terms of Service – CalciPro Usage Agreement & Policies",
  description: "Review the terms and conditions for using CalciPro calculators, website content, intellectual property rights, and service limitations on our platform.",
});

export default function TermsPage() {
  return (
    <main className="container mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <p className="text-sm font-black uppercase tracking-widest text-muted-foreground">Legal</p>
      <h1 className="mt-3 text-4xl font-black tracking-tight">Terms of Service</h1>
      
      <div className="mt-10 space-y-8 leading-7 text-muted-foreground">
        <section className="space-y-3">
          <h2 className="text-2xl font-black text-white">1. Agreement to Terms</h2>
          <p>By accessing or using CalciPro, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use our services.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-black text-white">2. Accuracy of Information</h2>
          <p>CalciPro provides calculators for informational and educational purposes only. While we strive for accuracy, we cannot guarantee that the results generated by our site are free from errors or omissions. Users should verify any results before making significant financial, health, or lifestyle decisions.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-black text-white">3. Intellectual Property</h2>
          <p>The content, organization, graphics, design, compilation, and other matters related to the Site are protected under applicable copyrights, trademarks, and other proprietary rights. You may use our calculators for personal use, but reproduction of our tools or content for commercial purposes without permission is strictly prohibited.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-black text-white">4. Disclaimer of Warranties</h2>
          <p>The site is provided on an "as-is" and "as-available" basis. We disclaim all warranties of any kind, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-black text-white">5. Limitation of Liability</h2>
          <p>In no event shall CalciPro be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in any way connected with the use of this website.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-black text-white">6. Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. Your continued use of the site following any such changes constitutes your acceptance of the new Terms of Service.</p>
        </section>
      </div>
    </main>
  );
}
